# Generated by Django 4.0.3 on 2022-04-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_password'),
        ('authentication', '0003_auto_20220331_1806'),
    ]

    operations = [
    ]
